### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by p0nce** [caraus-ecms/tanya#26]
- Does tanya has a link-time dependency on druntime?
- Does tanya has a link-time dependency on Phobos?
- Is Tanya suitable for disabled-runtime? (stronger restructions than `@nogc + runtime`, but less strong than -betterC)

**Comment by belka-ew** [comment]
> Does tanya has a link-time dependency on druntime?

Yes. Reimplementing the runtime or trying to adopt the library to a minimal runtime is too much work for now. It is an interesting experiment to provide a runtime as alternative that strips off unused features and maybe even doesn't depend on libc. But it would be a long-term goal, something that isn't feasible in the near term.

> Does tanya has a link-time dependency on Phobos?

Yes, there are still some algorithms from Phobos in use. Though it can change quickly; I was working on it from time to time and it is on my TODO list.

> Is Tanya suitable for disabled-runtime? (stronger restructions than @nogc + runtime, but less strong than -betterC)

Never tried, but probably not. I never had a need to disable the druntime completely. It is kind of cool to make tanya usable under more circumstances (and I would be very interested to know if someone tried :)), but there are currently more important things to do for me.

**Comment by p0nce** [comment]
Thanks for the answer. Fifty shades of `@nogc`. :)
