### ISSUE TITLE
The examples\echo crashed on Windows 10 X64

### ISSUE THREAD

**Issue by Heromyth** [caraus-ecms/tanya#32]
The example of echo works well for the x86_mscoff build mode:
> dub run --config=application --arch=x86_mscoff --build=debug --compiler=dmd

and will crash for the x86_64 build mode:
> dub run --config=application --arch=x86_64 --build=debug --compiler=dmd

OS： Windows 10 X64
Compiler: DMD v2.079.0

**Comment by belka-ew** [comment]
Confirmed. Thanks for the bug report. Can you test bugfix/bug32 branch please? it should fix this one.

**Comment by Heromyth** [comment]
It fixed. Thanks!
